### ISSUE TITLE
Fails Due to Additional Redirect

### ISSUE THREAD

**Issue by keplersj** [felixfbecker/semantic-release-firefox#36]
Hi @felixfbecker!

I'm attempting to use this plugin to publish an extension, and it looks like an additional redirect in-between `.../submit` and `/oauth/signin` is tripping up the login logic during `publish`. It looks to me that the submit page redirects to `/authorization` and then `/oauth/signin` when no user is logged in now.

[Repo Issue Was Found In](
https://github.com/keplersj/cises)
[Travis Job](https://travis-ci.org/keplersj/cises/jobs/506458198)

**Comment by felixfbecker** [comment]
Sounds plausible, PR welcome!
